2025-03-16 22:29:20,638 : INFO : root : Loading config.
2025-03-16 22:29:20,670 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-16 22:29:20,670 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\5682b9bdeb2b9ad8a31c13560e038609.mpf_cache
2025-03-16 22:29:20,686 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\coils.yaml
2025-03-16 22:29:20,686 : INFO : ConfigProcessor : Loading config from file C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\mpfconfig.yaml.
2025-03-16 22:29:20,732 : INFO : ConfigProcessor : Loading config: C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\mpfconfig.yaml
2025-03-16 22:29:20,732 : INFO : ConfigProcessor : Loading config from file C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\config.yaml.
2025-03-16 22:29:20,764 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\config.yaml
2025-03-16 22:29:20,779 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\lights.yaml
2025-03-16 22:29:20,811 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\coils.yaml
2025-03-16 22:29:20,826 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\switches.yaml
2025-03-16 22:29:20,873 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\images.yaml
2025-03-16 22:29:20,889 : INFO : ConfigProcessor : Loading config: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2\config\videos.yaml
2025-03-16 22:29:20,889 : INFO : ConfigProcessor : Config file cache created: C:\Users\User\AppData\Local\Temp\5682b9bdeb2b9ad8a31c13560e038609.mpf_cache
2025-03-16 22:29:21,138 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\8422c6572f827355f8aade1949d04025.mpf_cache
2025-03-16 22:29:21,154 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\1c0e7e9816717d8e62c4728dfe372999.mpf_cache
2025-03-16 22:29:21,170 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\e3e8065d662ad307fa9574659e7e4e8e.mpf_cache
2025-03-16 22:29:21,185 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\8422c6572f827355f8aade1949d04025.mpf_cache
2025-03-16 22:29:21,185 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-03-16 22:29:21,185 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-16-22-29-20-mpf-BERNIE.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\User\\Desktop\\fast_homebrew_godot_v2\\fast_homebrew_godot_v2\\logs\\2025-03-16-22-29-20-mpf-BERNIE.log'}
2025-03-16 22:29:21,185 : INFO : Machine : MPF path: C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf
2025-03-16 22:29:21,185 : INFO : Machine : Machine path: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2
2025-03-16 22:29:21,185 : INFO : Machine : Platform: win32
2025-03-16 22:29:21,185 : INFO : Machine : Python executable location: C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe
2025-03-16 22:29:21,185 : INFO : Machine : Python version: 3.12.3 (64-bit)
2025-03-16 22:29:21,201 : INFO : Machine : Initializing MPF...
2025-03-16 22:29:21,811 : INFO : FAST : Auto-detecting ports for the following connections: ['net']
2025-03-16 22:29:21,951 : ERROR : FAST [NET] : Failed to connect to any of the specified ports.
2025-03-16 22:29:21,951 : INFO : Machine : Shutting down...
2025-03-16 22:29:21,951 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-16 22:29:22,061 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\fast.py", line 277, in _connect_to_hardware
    await communicator.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 114, in connect
    raise SerialException(f"{self} could not connect to a serial port. Is it open in CoolTerm? ;)")
serial.serialutil.SerialException: [FAST NET] could not connect to a serial port. Is it open in CoolTerm? ;)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 686, in initialize_mpf
    raise init.exception()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 248, in initialize
    await self.initialize_core_and_hardware()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 244, in initialize_core_and_hardware
    await self._initialize_platforms()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 334, in _initialize_platforms
    result.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\fast.py", line 123, in initialize
    await self._connect_to_hardware()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\fast.py", line 284, in _connect_to_hardware
    raise MpfRuntimeError(f"Could not open serial port {port}. Is something else connected to the port? "
mpf.exceptions.runtime_error.MpfRuntimeError: Runtime Error in FAST: Could not open serial port net. Is something else connected to the port? Did the port number or your computer change? Do you have permissions to access the port? Error Code: RE-FAST-1 (https://missionpinball.org/logs)
2025-03-16 22:29:22,139 : INFO : root : MPF run loop ended.
