2025-03-15 16:03:07,404 : INFO : root : Loading config.
2025-03-15 16:03:07,414 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-15 16:03:07,414 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\5682b9bdeb2b9ad8a31c13560e038609.mpf_cache
2025-03-15 16:03:07,663 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\8422c6572f827355f8aade1949d04025.mpf_cache
2025-03-15 16:03:07,665 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\1c0e7e9816717d8e62c4728dfe372999.mpf_cache
2025-03-15 16:03:07,669 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\e3e8065d662ad307fa9574659e7e4e8e.mpf_cache
2025-03-15 16:03:07,669 : INFO : ConfigProcessor : Loading config from cache: C:\Users\User\AppData\Local\Temp\8422c6572f827355f8aade1949d04025.mpf_cache
2025-03-15 16:03:07,671 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-03-15 16:03:07,671 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-15-16-03-07-mpf-BERNIE.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\User\\Desktop\\fast_homebrew_godot_v2\\fast_homebrew_godot_v2\\logs\\2025-03-15-16-03-07-mpf-BERNIE.log'}
2025-03-15 16:03:07,672 : INFO : Machine : MPF path: C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf
2025-03-15 16:03:07,672 : INFO : Machine : Machine path: C:\Users\User\Desktop\fast_homebrew_godot_v2\fast_homebrew_godot_v2
2025-03-15 16:03:07,672 : INFO : Machine : Platform: win32
2025-03-15 16:03:07,672 : INFO : Machine : Python executable location: C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe
2025-03-15 16:03:07,672 : INFO : Machine : Python version: 3.12.3 (64-bit)
2025-03-15 16:03:07,677 : INFO : Machine : Initializing MPF...
2025-03-15 16:03:07,955 : INFO : FAST : Auto-detecting ports for the following connections: ['net']
2025-03-15 16:03:07,999 : INFO : FAST : Detected NET on port COM5
2025-03-15 16:03:08,109 : INFO : FAST [NET] : Trying to connect to COM5 at 921600bps
2025-03-15 16:03:08,119 : INFO : FAST [NET] : Connected to COM5 at 921600bps
2025-03-15 16:03:08,122 : INFO : FAST [NET] : Connected to FP-CPU-2000 with firmware v02.26
2025-03-15 16:03:08,153 : INFO : FAST [NET] : Registered I/O Board 0: Model: FP-I/O-3208, Firmware: 01.10, Switches: 32, Drivers: 8
2025-03-15 16:03:08,167 : INFO : FAST [NET] : Registered I/O Board 1: Model: FP-I/O-3208, Firmware: 01.10, Switches: 32, Drivers: 8
2025-03-15 16:03:08,168 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,239 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-15 16:03:08,239 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-15 16:03:08,239 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,239 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,241 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.3', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,504 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.22631-SP0', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.22631', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\User\\Desktop\\fast_homebrew_godot_v2\\fast_homebrew_godot_v2\\logs\\2025-03-15-16-03-07-mpf-BERNIE.log', 'prev_value': None, 'change': True}
2025-03-15 16:03:08,505 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-15 16:03:08,973 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe... Interface]')>) at C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:789
handle: <Handle Util.raise_exceptions(<Task finishe... Interface]')>) at C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:789>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py", line 797, in raise_exceptions
    future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 413, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 382, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 330, in _process_switch_closed
    self.machine.switch_controller.process_switch_by_num(state=1,
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\switch_controller.py", line 251, in process_switch_by_num
    raise AssertionError("Got early switch change for switch {} to state {}. platform: {}".format(
AssertionError: Got early switch change for switch 28 to state 1. platform: [FAST Platform Interface]
2025-03-15 16:03:09,083 : INFO : Machine : Starting the main run loop with active modes: []
2025-03-15 16:03:09,084 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-03-15 16:03:09,085 : INFO : Machine : Shutting down...
2025-03-15 16:03:09,085 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-15 16:03:10,180 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py", line 797, in raise_exceptions
    future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 413, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 382, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 330, in _process_switch_closed
    self.machine.switch_controller.process_switch_by_num(state=1,
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\switch_controller.py", line 251, in process_switch_by_num
    raise AssertionError("Got early switch change for switch {} to state {}. platform: {}".format(
AssertionError: Got early switch change for switch 28 to state 1. platform: [FAST Platform Interface]
2025-03-15 16:03:10,185 : INFO : root : MPF run loop ended.
